### ISSUE TITLE
проблема  с установкой MKS UI

### ISSUE THREAD

**Issue by kerukt** [Sergey1560/fb4s_howto#2]
не могу создать прошивку для flyingbear 5 c marlin 2.0.7.2 пытаясь все сделать по инструкции для mks ui, все время выходит ошибка #error "LCD_SET_PROGRESS_MANUALLY requires LCD_PROGRESS_BAR, Character LCD, Graphical LCD, TFT, or EXTENSIBLE_UI." и #error "FILAMENT_RUNOUT_SENSOR requires FIL_RUNOUT_PIN."
в конце выходит 
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL.cpp.o] Error 1
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\MarlinSerial.cpp.o] Error 1
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL_SPI.cpp.o] Error 1
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\SPI.cpp.o] Error 1

**Comment by Sergey1560** [comment]
Эта инструкция устарела. Готовая сборка с MKS UI с работающим wifi находится тут https://github.com/FBGhost-community/Marlin

Если вы все же хотите сделать это самостоятельно, отключите опции LCD_SET_PROGRESS_MANUALLY и FILAMENT_RUNOUT_SENSOR. Они реализованы внутри MKS UI.
